"""Generate docs/TAMIL_REVIEW.md -- the sheet a Tamil speaker signs off.

    python scripts/tamil_review_sheet.py            # write the sheet
    python scripts/tamil_review_sheet.py --check    # fail if it is stale

WHY THIS IS GENERATED AND NOT WRITTEN BY HAND
---------------------------------------------
orca/phrase_ta.py carries a standing REVIEW REQUIRED notice because no
test can tell you whether Tamil is *good* -- only whether it is present
and structurally correct. The review has to be done by a person.

A hand-written review document would be out of date the first time
someone edits a string, and a reviewer would sign off text the app no
longer says. Generating it from the module means the sheet always shows
exactly what a fisherman will see, and `--check` in CI catches a string
edited after sign-off.

This is a build-time generator for a committed artefact, like
scripts/build_colormaps.py. Nothing in orca/ or web/ imports it.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from data.fetch import ZONES              # noqa: E402
from orca import phrase_ta                # noqa: E402

OUT = Path(__file__).resolve().parent.parent / "docs" / "TAMIL_REVIEW.md"

HEADER = """# Tamil review sheet

**Generated by `scripts/tamil_review_sheet.py`. Do not edit by hand** --
edit `orca/phrase_ta.py` and regenerate, or your changes are lost and the
sign-off below stops meaning anything.

---

## What is being asked of you

Every Tamil sentence ORCA can say is listed below with its English
meaning. You are being asked three questions about each one, in order of
how much they matter:

1. **Is the meaning right?** Especially the negations. If a sentence that
   should say *"do not go"* can be read as *"you may go"*, someone could
   take a boat out in a 2.5 m sea. This is the only question that can
   get a person killed, so please read every DO NOT GO and CANNOT ASSESS
   line twice.
2. **Would a fisherman understand it immediately?** Not "is it correct
   Tamil" -- is it the Tamil someone hears over an engine and acts on.
   These strings are Modern Standard Tamil and were written for clarity,
   not for a coastal dialect. If a Nagapattinam or Rameswaram crew would
   say it differently, say so: that is the most useful thing you can give
   us.
3. **Is anything unnatural or machine-sounding?**

Harbour names are deliberately left in Latin script (Mandapam, not
மண்டபம்) inside answers, because that is how they appear on charts, boat
registrations and every sign at the landing centre. Tell us if that is
the wrong call.

**Nobody has reviewed these yet.** Until this sheet is signed at the
bottom, ORCA should not be described as a Tamil product.

---
"""

FOOTER = """
---

## Sign-off

| | |
|---|---|
| Reviewed by | _(name)_ |
| Dialect / region they speak | _(e.g. Nagapattinam coastal Tamil)_ |
| Date | _(YYYY-MM-DD)_ |
| Verdict | _(approved / approved with the changes below / not approved)_ |

### Changes requested

_(List the string id and what it should say instead. Then edit
`orca/phrase_ta.py`, re-run `python scripts/tamil_review_sheet.py`, and
re-check.)_
"""


def rows() -> list[tuple[str, str, str]]:
    """(id, Tamil, English meaning). Ordered most-safety-critical first."""
    out: list[tuple[str, str, str]] = []

    z1, z2 = "Mandapam", "Karaikal"
    out.append(("verdict.GO", phrase_ta.verdict("GO", z1, z1),
                "You may go fishing at Mandapam."))
    out.append(("verdict.DO_NOT_GO", phrase_ta.verdict("DO NOT GO", z1, None),
                "Do not go to Mandapam. No safer place was found nearby."))
    out.append(("verdict.SAFER_ALTERNATIVE", phrase_ta.verdict("SAFER ALTERNATIVE", z1, z2),
                "Do not go to Mandapam. Go to Karaikal instead, it is safer."))
    out.append(("verdict.BORDERLINE", phrase_ta.verdict("SAFER ALTERNATIVE", z1, z1),
                "Conditions at Mandapam are borderline. Go carefully, or wait."))
    out.append(("verdict.CANNOT_ASSESS_alt", phrase_ta.verdict("CANNOT ASSESS", z1, z2),
                "ORCA has no readings for Mandapam. Go to Karaikal instead."))
    out.append(("verdict.CANNOT_ASSESS", phrase_ta.verdict("CANNOT ASSESS", z1, None),
                "ORCA has no readings for Mandapam, so it cannot say anything. "
                "This does NOT mean it is safe. Do not treat it as safe."))
    out.append(("verdict.UNKNOWN", phrase_ta.verdict("???", z1, None),
                "ORCA cannot give an answer right now."))

    for key, text in phrase_ta.IMBL.items():
        out.append((f"boundary.{key}", text.format(km="4"),
                    phrase_ta.IMBL_EN[key].format(km="4")
                    + "  (spoken aloud by the phone while the app is closed)"))

    out.append(("lookup.value", phrase_ta.data_lookup_sentence(
        {"variable": "wave_height_m", "value": 1.6, "unit": "m"}, "Thoothukudi"),
        "The wave height at Thoothukudi is 1.6 metres."))
    out.append(("lookup.missing", phrase_ta.data_lookup_sentence(
        {"variable": "chlorophyll_mg_m3", "time_frame": "tomorrow", "missing": True},
        "Karaikal"),
        "ORCA has no chlorophyll reading for tomorrow at Karaikal."))

    out.append(("ranking.highest", phrase_ta.ranking_sentence(
        {"zone": "Thoothukudi", "value": 1.6, "unit": "m"}, 10, "wave_height_m", True),
        "Of the 10 places ORCA covers, Thoothukudi has the highest wave height: 1.6 m."))
    out.append(("ranking.lowest", phrase_ta.ranking_sentence(
        {"zone": "Cuddalore", "value": 0.4, "unit": "m"}, 10, "wave_height_m", False),
        "Of the 10 places ORCA covers, Cuddalore has the lowest wave height: 0.4 m."))
    out.append(("ranking.risk", phrase_ta.ranking_sentence(
        {"zone": "Mandapam", "action": "SAFER ALTERNATIVE"}, 10, None, True),
        "Of the 10 places ORCA covers, Mandapam is currently the most dangerous."))

    out.append(("off_topic", phrase_ta.OFF_TOPIC,
                "ORCA only answers questions about sea conditions and whether it is "
                "safe to go fishing. Ask about that."))

    note_glosses = {
        "fallback": "You did not name a place ORCA covers, so this answer is for Mandapam.",
        "beyond": "ORCA only has readings for today and tomorrow, so this is today's condition.",
        "stale_forecast": "ORCA has no forecast for tomorrow, so this is today's condition.",
        "route": "ORCA has no route guidance.",
        "tide_or_time": "ORCA has no tide tables or timings.",
        "species": "ORCA has no fish-species information.",
        "unit_conversion": "Each reading is given in the unit its source publishes.",
        "offline": "No internet -- showing saved information.",
        "seed": "No internet -- showing the information that came with the app.",
    }
    for key, text in phrase_ta.NOTES.items():
        out.append((f"note.{key}", text.format(zone="Mandapam"),
                    note_glosses.get(key, "")))

    for variable, text in phrase_ta.READABLE.items():
        out.append((f"variable.{variable}", text, variable))

    for raw, text in phrase_ta.UNIT.items():
        out.append((f"unit.{raw}", text, raw))

    return out


def render() -> str:
    parts = [HEADER]

    parts.append("\n## Sentences ORCA says\n")
    parts.append("| id | Tamil | English meaning |")
    parts.append("|---|---|---|")
    for key, tamil, english in rows():
        if key.startswith(("variable.", "unit.")):
            continue
        parts.append(f"| `{key}` | {tamil} | {english} |")

    parts.append("\n## Words for each reading\n")
    parts.append("| id | Tamil | Meaning |")
    parts.append("|---|---|---|")
    for key, tamil, english in rows():
        if key.startswith("variable."):
            parts.append(f"| `{key}` | {tamil} | {english} |")

    parts.append("\n## Units\n")
    parts.append("| id | Tamil | Meaning |")
    parts.append("|---|---|---|")
    for key, tamil, english in rows():
        if key.startswith("unit."):
            parts.append(f"| `{key}` | {tamil} | {english} |")

    parts.append("\n## Harbour names in Tamil\n")
    parts.append(
        "These are the Tamil spellings ORCA MATCHES when someone types or "
        "speaks a question. They are stems, not full words, so that "
        "inflected forms match too (நாகப்பட்டினம் / நாகப்பட்டினத்தில்). If a "
        "spelling here is one nobody uses, the app will not understand that "
        "question at all -- so a missing spelling matters as much as a wrong "
        "sentence.\n"
    )
    parts.append("| Tamil stem | Matches zone |")
    parts.append("|---|---|")
    for stem, name in phrase_ta.ZONE_STEMS_TA.items():
        parts.append(f"| {stem} | {name} |")
    covered = set(phrase_ta.ZONE_STEMS_TA.values())
    missing = [z["name"] for z in ZONES if z["name"] not in covered]
    if missing:
        parts.append(f"\n**Not yet reachable in Tamil:** {', '.join(missing)}")

    parts.append(FOOTER)
    return "\n".join(parts) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="fail if the committed sheet does not match orca/phrase_ta.py")
    args = ap.parse_args()

    generated = render()
    if args.check:
        if not OUT.exists():
            print(f"MISSING: {OUT}", file=sys.stderr)
            print("Run: python scripts/tamil_review_sheet.py", file=sys.stderr)
            return 1
        if OUT.read_text(encoding="utf-8") != generated:
            print("STALE: docs/TAMIL_REVIEW.md does not match orca/phrase_ta.py.",
                  file=sys.stderr)
            print("A string changed after the sheet was generated, so any sign-off "
                  "on it no longer covers what the app says.", file=sys.stderr)
            print("Run: python scripts/tamil_review_sheet.py", file=sys.stderr)
            return 1
        print(f"OK: {OUT.name} matches orca/phrase_ta.py")
        return 0

    OUT.write_text(generated, encoding="utf-8")
    print(f"Wrote {OUT} ({len(generated)} bytes, {len(rows())} strings)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
